services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
      network: host
    container_name: user-management-app
    restart: always
    network_mode: host
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5051
      DB_USER: root
      DB_PASSWORD: Humph2026!Secure
      DB_NAME: user_management
      JWT_SECRET: humphrey_secret_key_2026
      PORT: 5050